# Generated by Django 4.2.11 on 2024-04-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graficos_megafax', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='br',
            name='hour',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
