# Generated by Django 4.2.11 on 2024-04-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graficos_isdbt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nombre',
            name='canal_id',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
