# Generated by Django 4.2.11 on 2024-04-17 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graficos_isdbt', '0002_nombre_canal_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='nombre',
            new_name='BR_isdbt',
        ),
    ]
