# Generated by Django 4.2.11 on 2024-04-17 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graficos_isdbt', '0003_rename_nombre_br_isdbt'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BR_isdbt',
            new_name='BR',
        ),
    ]
