# Generated by Django 4.2.11 on 2024-04-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graficos_isdbt', '0004_rename_br_isdbt_br'),
    ]

    operations = [
        migrations.AddField(
            model_name='br',
            name='hour',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
